### PR TITLE
GIANT BREAKING CHANGE: Here the implementation is just a port of react-flatpickr

### PR DESCRIPTION
**Pull request by rosenbjerg**
It works great for me, so I think we should just use their implementation ported to preact?

### CODE REVIEW

**Comment by molnarmark** [comment]
Why should we add another dependency? that being react-flatpickr. Is there a benefit of doing this?

**Comment by rosenbjerg** [comment]
Just for better error info, but we could easily cut that part out?

**Comment by molnarmark** [comment]
I have just added you as a contributor to the project. I feel like you can handle this more easily as you have specific use cases.

**Comment by rosenbjerg** [comment]
Thank you. How do you feel about this major change? Would you prefer we remove the prop-types dependency and usage? I can see reason to keep it and to remove it, so it is up to you. We can always add later if we don't include it now

**Comment by rosenbjerg** [comment]
I did like your idea about the theme prop automatically importing the needed style sheet, so I will add that to the ported code. But perhaps without a default, so users familiar with react-flatpickr also feel at home using this if they switch to preact? So if the theme-prop is used the style will be imported, but otherwise we assume that the user imports it themselves

**Comment by molnarmark** [comment]
I'm giving you full access to everything. Since I dont use Preact in production, I dont know the use cases a user would need to make the integration seems possible. If there is anything you can do to make that integration more flexible, go ahead :)

**Comment by rosenbjerg** [comment]
The changes have been adjusted and added

**Pull request closed without merging**
